#!/bin/bash
# sudo apt install bc
# sudo apt install
# sudo apt install make
# sudo apt install zlib1g-dev
# sudo apt install r-base-core

# Get the directory of the script
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

# Source necessary files
. $SCRIPT_DIR/functions.sh
. $SCRIPT_DIR/config.sh


# --- Help Function
usage() # This is the help function
{
   # Display Help
   echo "========================================= Run ADMIXTURE Pipeline =============================================="
   echo "                usage: run_geomap.sh [-h] [ARGS]                                                               "
   echo "                example: ./run_geomap -k 5 -f results/reference_admixture/K5/ -r results/cohort_admixture/DNA35_validation/ -i results/cohort_admixture/DNA35_validation/ -v "
   echo "                                  -k       Value selected for number of populations.                           "
   echo "                                  -f       Path to the folder with all .Q files.                               "
   echo "                                  -r       Path to the research cohort .Q file.                                "
   echo "                                  -i       Path to the research cohort .fam file.                              "
   echo "                                  -o       Path to the folder into which results are saved.                    "
   echo "                                  -v       If set to 1, runs the software verbously.                           "
   echo "                                  -V       Prints out the tool version.                                        "
   echo "                                  -h       Print this Help.                                                    "
   echo "                                                                                                               "
   echo "==============================================================================================================="
}

while getopts ":hk:f:r:i:o:vV" flag;
do
    case "${flag}" in
        h) # Display Help Function
              usage
              exit;;
        k)
              k_pops=${OPTARG}
        ;;
        f)
              ref_qfolder=${OPTARG}
        ;;
        r)
              res_qfolder=${OPTARG}
        ;;
        i)
              famfile=${OPTARG}
        ;;
        o)
              outfolder=${OPTARG}
        ;;
        v)
              verbose=1
        ;;
        V)
              VERSION="version"
              echo $VERSION
        ;;
        ?)
          echo "Error: Invalid option. Try '-h' to see a list of available options."
          exit;;
        *)
          usage
          exit;;
    esac
done

# Change directory to the script dir
cd "$SCRIPT_DIR" || exit

# Generate the input file in plink format
if [ -z "$OUTFOLDER" ]
  then
    OUT="$SCRIPT_DIR/results/geomap"
  else
    OUT="$SCRIPT_DIR/results/$OUTFOLDER/geomap"
fi

if [ -z "$verbose" ]
  then
    verbose=0
fi

##### RUN PLINK #####
# Create folder to hold the PLINK binaries
make_dir $OUT

Rscript $RSCRIPTS/geomap.R -k $k_pops -f $ref_qfolder -r $res_qfolder -i $famfile -o $OUT -v $verbose

# Redirects output to out.log and errors to error.log
# command > out.log 2> error.log
